// Generated by React Router

import 'react-router';

declare module 'react-router' {
  interface Register {
    pages: Pages;
    routeFiles: RouteFiles;
    routeModules: RouteModules;
  }
}

type Pages = {
  '/': {
    params: {};
  };
  '/survey': {
    params: {};
  };
  '/recommendations': {
    params: {};
  };
  '/products/:productId': {
    params: {
      productId: string;
    };
  };
};

type RouteFiles = {
  'root.tsx': {
    id: 'root';
    page: '/' | '/survey' | '/recommendations' | '/products/:productId';
  };
  'routes/onboarding/index.tsx': {
    id: 'routes/onboarding/index';
    page: '/';
  };
  'routes/survey/index.tsx': {
    id: 'routes/survey/index';
    page: '/survey';
  };
  'routes/recommendations/index.tsx': {
    id: 'routes/recommendations/index';
    page: '/recommendations';
  };
  'routes/products/detail.tsx': {
    id: 'routes/products/detail';
    page: '/products/:productId';
  };
};

type RouteModules = {
  root: typeof import('./src/app/root.tsx');
  'routes/onboarding/index': typeof import('./src/app/routes/onboarding/index.tsx');
  'routes/survey/index': typeof import('./src/app/routes/survey/index.tsx');
  'routes/recommendations/index': typeof import('./src/app/routes/recommendations/index.tsx');
  'routes/products/detail': typeof import('./src/app/routes/products/detail.tsx');
};
