// Generated by React Router

import 'react-router';

declare module 'react-router' {
  interface Register {
    pages: Pages;
    routeFiles: RouteFiles;
    routeModules: RouteModules;
  }
}

type Pages = {
  '/': {
    params: {};
  };
  '/login': {
    params: {};
  };
};

type RouteFiles = {
  'root.tsx': {
    id: 'root';
    page: '/' | '/login';
  };
  'layouts/PublicLayout.tsx': {
    id: 'layouts/PublicLayout';
    page: '/login';
  };
  'routes/(public)/login/index.tsx': {
    id: 'routes/(public)/login/index';
    page: '/login';
  };
  'layouts/PrivateLayout.tsx': {
    id: 'layouts/PrivateLayout';
    page: '/';
  };
  'routes/(private)/home/index.tsx': {
    id: 'routes/(private)/home/index';
    page: '/';
  };
};

type RouteModules = {
  root: typeof import('./src/app/root.tsx');
  'layouts/PublicLayout': typeof import('./src/app/layouts/PublicLayout.tsx');
  'routes/(public)/login/index': typeof import('./src/app/routes/(public)/login/index.tsx');
  'layouts/PrivateLayout': typeof import('./src/app/layouts/PrivateLayout.tsx');
  'routes/(private)/home/index': typeof import('./src/app/routes/(private)/home/index.tsx');
};
